name: reflect

up:
  - node
  - npm
  - custom:
      name: "setup environment"
      met?: "test -f .env"
      meet: "cp .env.example .env"

test:
  run: "npm run test"
  subcommands:
    watch: "npm run test:watch"
    coverage: "npm run test:coverage"

check:
  typecheck: "npm run typecheck"

console: "npx tsx bin/console.ts"

open:
  ci: "https://github.com/bostonaholic/reflect/actions"
